import type { Metadata } from "next";
import Layout from "@/components/layout/layout";
import '@/app/globals.css'
import { CartProvider } from "@/contexts/cart-context";
import { SearchProvider } from "@/components/marketplace/search-sidebar/search-sidebar-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Layout>
            <SearchProvider>
              <main>
                {children}
              </main>
            </SearchProvider>
          </Layout>
        </CartProvider>
      </body>
    </html>
  );
}
